- name: Set Up Web Server and Content
  hosts: all
  become: yes
  become_method: sudo
  remote_user: root

  tasks:
    - import_tasks: tasks/install_nginx.yaml
    # - name: Ensure Web Server is Running
    #   systemd:
    #     name: nginx
    #     state: started
    #     enabled: yes
    - name: Create hw1 content for Red Team
      ansible.builtin.copy:
        src: "src/hw1_red.html"
        dest: "/var/www/html/hw1.html"
      when: "'red' in group_names"
    - name: Create hw1 content for Blue Team
      ansible.builtin.copy:
        src: "src/hw1_blue.html"
        dest: "/var/www/html/hw1.html"
      when: "'blue' in group_names"
    - name: Install Curl
      apt:
        name: curl
        state: present
