# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    network_mode: host # default port is 3306
  flask:
    build: .
    network_mode: host
